a = int(input())
b = 5
print(f"{a} += 1 = {a + 1}")
print(f"{a} -= 1 = {a - 1}")
print(f"{a} += {b} = {a + b}")
print(f"{a} *= {b} = {a * b}")
print(f"{a} /= {b} = {a / b}")
print(f"{a} %= {b} = {a % b}")
print(f"{a} **= {b} = {a ** b}")
print(f"{a} //= {b} = {a // b}")
